import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import BasicTabs from '../components/Header';
import Footer from '../components/Footer';
import { Button, Container, Stack } from '@mui/material';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Line } from 'react-chartjs-2';
import WordCloud from 'react-d3-cloud';

import faker from 'faker';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

const Home: NextPage = () => {
  const instance = axios.create({
    baseURL: 'https://3.18.104.128:5000',
  });

  const options = {
    responsive: true,
    plugins: {
      legend: {
        position: 'top' as const,
      },
      title: {
        display: true,
        text: 'Chart.js Line Chart',
      },
    },
  };
  const cloudData = [
    { text: 'Hey', value: 1000 },
    { text: 'lol', value: 200 },
    { text: 'first impression', value: 800 },
    { text: 'very cool', value: 1000000 },
    { text: 'duck', value: 10 },
  ];
  const labels = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
  ];

  const data = {
    labels,
    datasets: [
      {
        label: 'Dataset 1',
        data: labels.map(() =>
          faker.datatype.number({ min: -1000, max: 1000 })
        ),
        borderColor: 'rgb(255, 99, 132)',
        backgroundColor: 'rgba(255, 99, 132, 0.5)',
      },
      {
        label: 'Dataset 2',
        data: labels.map(() =>
          faker.datatype.number({ min: -1000, max: 1000 })
        ),
        borderColor: 'rgb(53, 162, 235)',
        backgroundColor: 'rgba(53, 162, 235, 0.5)',
      },
    ],
  };

  return (
    <Container fixed>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
        />
      </Head>
      <BasicTabs />
      <Stack spacing={2}>
        <section
          style={{ height: 'fitContent', width: '100%', border: 'solid 1px #000' }}
        >
          암호화페 키워드
          {typeof window === 'object' ? (
            <WordCloud data={cloudData} />
          ) : (
            ''
          )}
        </section>
        <section
          style={{ height: '100px', width: '100%', border: 'solid 1px #000' }}
        >
          해외주식 키워드
        </section>
        <section className={styles.bitCoinCart}>
          비트코인
          <Line options={options} data={data} />
        </section>
        <section
          style={{ height: '100px', width: '100%', border: 'solid 1px #000' }}
        >
          텍스트 감성 분석 차트
        </section>
        <section
          style={{ height: '400px', width: '100%', border: 'solid 1px #000' }}
        >
          뉴스
        </section>
        <Button
          onClick={async () => {
            try {
              const data = await instance.get('/bitgal/retrieval');
              console.log(data);
            } catch (err) {
              console.log('err:', err);
            }
          }}
        >
          getApis
        </Button>
      </Stack>
      <Footer />
    </Container>
  );
};

export default Home;
